apiVersion: v1
kind: Service
metadata:
  name: web-mini-svc
spec:
  type: NodePort
  selector:
    app: web-mini
  ports:
    - port: 80           # container listens on 80
      targetPort: 80
      nodePort: 30080    # exposed on the host via kind-config.yaml
